### ISSUE TITLE
Another problem

### ISSUE THREAD

**Issue by groesie** [AmirHosein-Gharaati/Competitive-programming#1]
Hi. Thanks for your repo.
I am new to competitive programming, and on one platform I came across the following problem. I would be grateful for advice in its optimal solution.

Two binary matrices are given. You need to bring them to the same size and count the number of differences. There can be up to 10^6 elements in the matrix.

For example, for the following two matrices
110 11
000
the answer is 8 (the final size is 2x6).

It is clear that they can be reduced to the same size using the Euclidean algorithm, but I have no further ideas.

**Comment by AmirHosein-Gharaati** [comment]
Hi, I didn't fully understand your problem.
Isn't there any problem on kattis or uva or . . . to check the full problem ?

**Comment by groesie** [comment]
Hi. In the example in the first matrix, the elements doubled, it turned
out
111100
00000
in the second, the elements tripled, and the string split into two
111111
111111
In the worst case, if the dimensions of the matrices are mutually simple, then the size of the resulting matrices can be 10^12, and this is a problem

**Comment by AmirHosein-Gharaati** [comment]
Unfortunately I don't understand your problem, If you had a reference, please send the link for me.
